### ISSUE TITLE
Mac平台

### ISSUE THREAD

**Issue by mifanj** [oliyg/juejinxiaoce#1]
执行 npm i 后会下载Chromium到node_modules/puppeteer/.local-chromium/mac-609904/chrome-mac
将chrome-mac直接复制到项目根目录

目录结构如下
├── chrome-mac
├── dist
├── node_modules
├── CODE_OF_CONDUCT.md
├── LICENSE
├── app.js
├── constant.js
├── converter.js
├── package-lock.json
├── package.json
└── readme.md

然后将根目录下app.js中第17行
executablePath: './chrome-win/chrome.exe',
替换为
executablePath: './chrome-mac/Chromium.app/Contents/MacOS/Chromium',

保存后执行 npm start

等待结束即可

ps:过程中下载html文件时提示all finished:  false，不确定是否判断条件未适配macOS系统，但完成后并没有什么问题

感谢git主的辛勤劳动和无私精神！

**Comment by oliyg** [comment]
已修复 将puppeteer 替换成了 pupeteer-core ，还是手动下载，将文件放在 mac 对应的 chrome-mac 文件夹中即可
