### ISSUE TITLE
 (node:15958) UnhandledPromiseRejectionWarning: Error: spawn EACCES

### ISSUE THREAD

**Issue by wsdo** [oliyg/juejinxiaoce#2]
![image](https://user-images.githubusercontent.com/9738969/51517946-58a97780-1e57-11e9-97c6-8a84e5a7074b.png)

**Comment by oliyg** [comment]
尝试手动安装 Chromium 并将 pupeteer 的 path 指向 `/Applications/Chromium.app/Contents/MacOS/Chromium`

> 随后将解决这个问题

**Comment by oliyg** [comment]
请阅读更新后的 readme.md

**Comment by wsdo** [comment]
不能解决问题， 手动安装的放在项目里面了

**Comment by oliyg** [comment]
> 不能解决问题， 手动安装的放在项目里面了

需要将 chromium 安装到系统应用程序文件夹中 放项目里不行

见  [issue](https://github.com/GoogleChrome/puppeteer/issues/1649)
